#!/usr/bin/env python3
"""Generate .github/CODEOWNERS so each ADLC artifact is routed to its approver team.

  setup_codeowners.py            write the file
  setup_codeowners.py --check    exit 1 if the file is missing or out of date

Also prints the branch protection settings the repository needs. Teams come from
config/governance/gate_roles.json > github_teams.
"""
from __future__ import annotations

import argparse
import sys

from _common import load_json, repo_root

HEADER = "# Generated by .claude/skills/adlc/scripts/setup_codeowners.py. Edit gate_roles.json, then re-run.\n"


def render(root) -> str:
    cfg = load_json(root / "config/governance/gate_roles.json")
    teams = cfg.get("github_teams", {})
    lines = [HEADER, "# ADLC phase artifacts: each is approved by its gate role.\n"]
    for gate, spec in cfg["gates"].items():
        owners = " ".join(teams[r] for r in spec["roles"] if r in teams)
        lines.append(f"/{spec['artifact']}  {owners}  # {gate}\n")
    lines.append(f"/adlc/adr/  {teams.get('architect', '')}  # G2 decisions\n")
    lines.append("\n# The gate configuration itself needs a security officer and a waiver approver.\n")
    lines.append(f"/config/governance/  {teams.get('security_officer', '')} {teams.get('waiver_approver', '')}\n")
    lines.append(f"/.github/CODEOWNERS  {teams.get('security_officer', '')} {teams.get('waiver_approver', '')}\n")
    return "".join(lines)


PROTECTION = """Branch protection for the default branch (Settings > Rules):
  - Require a pull request before merging
  - Require review from Code Owners
  - Dismiss stale pull request approvals when new commits are pushed
  - Require approval of the most recent reviewable push
  - Do not allow bypassing the above settings
These make each gate a named-role approval that the author cannot give themselves."""


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args()
    root = repo_root()
    target = root / load_json(root / "config/project_config.json").get("github", {}).get("codeowners_path", ".github/CODEOWNERS")
    content = render(root)
    if args.check:
        ok = target.exists() and target.read_text(encoding="utf-8") == content
        print("CODEOWNERS is up to date." if ok else f"{target.relative_to(root)} is missing or out of date. Run setup_codeowners.py.")
        return 0 if ok else 1
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(content, encoding="utf-8")
    print(f"Wrote {target.relative_to(root)}.\n\n{PROTECTION}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
